//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFiado.Exceptions.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectFiado.Exceptions.ErrorMessages.ProductErrorMessages", typeof(ProductErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the product cannot be null or empty.
        /// </summary>
        internal static string Error_01___Product_Empty {
            get {
                return ResourceManager.GetString("Error 01 - Product Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product name is null.
        /// </summary>
        internal static string Error_02___Product_Empty_Name {
            get {
                return ResourceManager.GetString("Error 02 - Product Empty Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product price is invalid or null.
        /// </summary>
        internal static string Error_03____Product_Price_Invalid {
            get {
                return ResourceManager.GetString("Error 03  - Product Price Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product brand is null.
        /// </summary>
        internal static string Error_04___Product_Brand_Empty {
            get {
                return ResourceManager.GetString("Error 04 - Product Brand Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is null.
        /// </summary>
        internal static string Error_05___Product_Description_empty {
            get {
                return ResourceManager.GetString("Error 05 - Product Description empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        internal static string Error_06_Product_not_Found {
            get {
                return ResourceManager.GetString("Error 06 Product not Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No products found..
        /// </summary>
        internal static string Error_07_Products_not_found_List {
            get {
                return ResourceManager.GetString("Error 07 Products not found List", resourceCulture);
            }
        }
    }
}
